### ISSUE TITLE
We have to add parser

### ISSUE THREAD

**Issue by EugeneDar** [objectionary/flatty#23]
We need structure which will take phi calculus in string format and parse it to tree of entities.

**Comment by 0pdd** [comment]
@EugeneDar the puzzle [#37](https://github.com/objectionary/flatty/issues/37) is still not solved.

**Comment by 0pdd** [comment]
@EugeneDar 2 puzzles [#37](https://github.com/objectionary/flatty/issues/37), [#62](https://github.com/objectionary/flatty/issues/62) are still not solved.
