### ISSUE TITLE
We need structure for objects storage

### ISSUE THREAD

**Issue by EugeneDar** [objectionary/flatty#25]
For future work with objects we need such a data structure.

**Comment by 0pdd** [comment]
@EugeneDar the puzzle [#28](https://github.com/objectionary/flatty/issues/28) is still not solved; solved: [#29](https://github.com/objectionary/flatty/issues/29).

**Comment by 0pdd** [comment]
@EugeneDar all 2 puzzles are solved here: [#28](https://github.com/objectionary/flatty/issues/28), [#29](https://github.com/objectionary/flatty/issues/29).
