### ISSUE TITLE
We need a class to check token types

### ISSUE THREAD

**Issue by EugeneDar** [objectionary/flatty#41]
We need methods like: `isLocator`, `isLambda`, etc..

**Comment by 0pdd** [comment]
@EugeneDar 5 puzzles [#43](https://github.com/objectionary/flatty/issues/43), [#44](https://github.com/objectionary/flatty/issues/44), [#45](https://github.com/objectionary/flatty/issues/45), [#46](https://github.com/objectionary/flatty/issues/46), [#47](https://github.com/objectionary/flatty/issues/47) are still not solved.

**Comment by 0pdd** [comment]
@EugeneDar all 5 puzzles are solved here: [#43](https://github.com/objectionary/flatty/issues/43), [#44](https://github.com/objectionary/flatty/issues/44), [#45](https://github.com/objectionary/flatty/issues/45), [#46](https://github.com/objectionary/flatty/issues/46), [#47](https://github.com/objectionary/flatty/issues/47).
